---
# playbook.yml
- name: 'Provision Custom Image'
  hosts: default
  become: true

  tasks:
    - name: install Apache
      package:
        name: 'apache2'
        state: present

    - name: Start Apache Service
      service:
        name: apache2
        state: started
        enabled: true

    - name: print simple msg
      command: echo 'Hello From Packer'

